# permissions for end users to view harborregistryconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harborregistryconfiguration-viewer-role
rules:
- apiGroups:
  - harbor-configuration.harbor-practice.co.uk
  resources:
  - harborregistryconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - harbor-configuration.harbor-practice.co.uk
  resources:
  - harborregistryconfigurations/status
  verbs:
  - get
