---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - harbor-configuration.harbor-practice.co.uk
  resources:
  - harborregistryconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harbor-configuration.harbor-practice.co.uk
  resources:
  - harborregistryconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - harbor-configuration.harbor-practice.co.uk
  resources:
  - harborregistryconfigurations/status
  verbs:
  - get
  - patch
  - update
